export const defaultLang = 'nl';
export const supportedLangs = ['nl', 'en'];

export const routes = {
  nl: {
    about: 'over-ons',
    portfolio: 'portfolio',
    pricing: 'prijzen',
    contact: 'contact',
    timeline: 'tijdlijn',
  },
  en: {
    about: 'about',
    portfolio: 'portfolio',
    pricing: 'pricing',
    contact: 'contact',
    timeline: 'timeline',
  },
} as const;

export const ui = {
  en: {
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.portfolio': 'Portfolio',
    'nav.pricing': 'Pricing',
    'nav.timeline': 'Timeline',
    'nav.contact': 'Contact',
    'hero.title': 'Your Partner in Digital Innovation.',
    'hero.subtitle': 'We build fast, modern websites that deliver results.',
    'hero.cta': 'Get in Touch',
    'contact.title': 'Contact Us',
    'contact.description': 'Reach out for inquiries or quotes.',
    'contact.heading': 'Send us a message',
    'contact.subtitle': 'We will respond as soon as possible.',
    'contact.name': 'Name',
    'contact.namePlaceholder': 'Your full name',
    'contact.email': 'Email',
    'contact.emailPlaceholder': 'you@example.com',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Write your message here...',
    'contact.submit': 'Send Message',
    page_not_found: 'Page not found',
    back_home: 'Back to home',
  },
  nl: {
    'nav.home': 'Home',
    'nav.about': 'Over Ons',
    'nav.portfolio': 'Portfolio',
    'nav.pricing': 'Prijzen',
    'nav.timeline': 'Tijdlijn',
    'nav.contact': 'Contact',
    'hero.title': 'Uw Partner in Digitale Innovatie.',
    'hero.subtitle': 'Wij bouwen snelle, moderne websites die resultaten leveren.',
    'hero.cta': 'Neem Contact Op',
    'contact.title': 'Contact',
    'contact.description': 'Neem contact met ons op voor vragen of offertes.',
    'contact.heading': 'Stuur ons een bericht',
    'contact.subtitle': 'We nemen zo snel mogelijk contact met u op.',
    'contact.name': 'Naam',
    'contact.namePlaceholder': 'Uw volledige naam',
    'contact.email': 'E-mail',
    'contact.emailPlaceholder': 'u@voorbeeld.com',
    'contact.message': 'Bericht',
    'contact.messagePlaceholder': 'Schrijf hier uw bericht...',
    'contact.submit': 'Verstuur bericht',
    page_not_found: 'Pagina niet gevonden',
    back_home: 'Terug naar home',
  },
} as const;